# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a31a4aee5842da0e7df5f1d636ca3773478d660ad6acba6c1a051bce040a01bae226ba45772e410015b0a0a382629aca43e712151e4afd17e272bf15de3bac7

test:
  secret_key_base: 9d98ed6f9482a650efe56fb338e629fb71ab88ef7b392304454d638b163aba1dbc04c19d592accbb183ba5011802f1585876980b0aa735d3dea000a1849107be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
